version: '3.8'  # Specify the version of docker-compose

services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    networks:
      - dynamo-network
  dynamodb:
    image: "aaronshaf/dynamodb-admin"
    container_name: dynamodb-admin
    depends_on:
      - dynamodb-local
    restart: always
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
      - AWS_ACCESS_KEY_ID=YourAccessKey
      - AWS_SECRET_ACCESS_KEY=YourSecretKey
    networks:
      - dynamo-network
    
  dynamodbsample:
    image: dynamodbsample
    container_name: dynamodb-api
    depends_on:
      - dynamodb-local
    build:
      context: .
      dockerfile: DynamoDbSample/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "8080:80"
    networks:
      - dynamo-network

networks:
  dynamo-network:
    driver: bridge
